### ISSUE TITLE
cool issue

### ISSUE THREAD

**Issue by lindseywild** [lindseywild/commenting-workflow-test#47]
### Description

This is a random sample of Aware issues that were validated by @lindseywild from the [HCL-UNISE-SEP2022](https://github.com/github/accessibility-audits/issues?q=is%3Aissue+label%3AHCL-UNISE-SEP2022) audit.

Validator: please verify that the following issues have been accurately validated and closed. If you find something incorrect, please add a comment to this issue.

### Issues

- [ ] [[WCAG Audit] [UNISE2.10] [Usable- Unified search- Results page- Save search] Asterisk indicator is not visually present alongside the label of ‘Query’ input field.](https://github.com/github/accessibility-audits/issues/2805)
- [ ] [[WCAG Audit] [UNISE2.10] [Keyboard Navigation- Unified search- Results page- Save search] Upon collapsing the expanded 'Create saved search' dialog box using esc key, focus disappears and does not retain back to 'Save search' control.](https://github.com/github/accessibility-audits/issues/2809)
- [ ] [[WCAG Audit] [UNISE2.11] [Programmatic Access- Unified search- Results page- filter by/state] Screen reader does not announce any information upon activating 'Closed' control present under 'State' of 'Filter by' section.](https://github.com/github/accessibility-audits/issues/2813)
- [ ] [[WCAG Audit] [UNISE2.4] [Programmatic Access- Unified search- Results page- Search] For 'Search across repositories' dropdown, state- expanded/collapsed control (^) and role is not defined.](https://github.com/github/accessibility-audits/issues/2814)
- [ ] [[WCAG Audit] [UNISE2.9] [Screen Reader- Unified search- Results page- Repositories- Sort: Best match] The focus of screen reader (NVDA) does not move from browse mode to focus mode automatically when 'Sort' dropdown is activated.](https://github.com/github/accessibility-audits/issues/2817)
