### ISSUE TITLE
Audit issue verification for @lindseywild

### ISSUE THREAD

**Issue by lindseywild** [lindseywild/commenting-workflow-test#50]
### Description

This is a random sample of audit issues that were validated by @lindseywild.

Validator: please verify that the following issues have been accurately validated and closed. If you find something incorrect, please add a comment to this issue.

### Issues

- [ ] [[WCAG Audit] [NPMSEMPG1.4] [Keyboard Navigation- NPM semver Page- submit] No error message is displayed upon providing an invalid input in the 'pick a package' edit field.  ](https://github.com/github/accessibility-audits/issues/2875)
- [ ] [[WCAG Audit] [NPMSEMPG1.4] [Usable- NPM semver Page- submit] 'Pick a package' name is not suitable as per its association with an input field.](https://github.com/github/accessibility-audits/issues/2873)
- [ ] [[WCAG Audit] [CODENAV1.12] [Screen Reader-Code/Nov-Symbols-Vector Widget] Screen Reader is not announcing the expand/collapse information of the Vector Widget treeitem element. ](https://github.com/github/accessibility-audits/issues/2983)
- [ ] [[WCAG Audit] [NPMSEMPG1.1] [Programmatic Access- NPM semver Page] There are no landmarks defined for 'npm semver calculator' page.](https://github.com/github/accessibility-audits/issues/2870)
- [ ] [[WCAG Audit] [NPMSEMPG1.4] [Screen Reader- NPM semver Page- submit] Upon activation 'Submit' button, screen reader is not announcing any information for the already provided input.](https://github.com/github/accessibility-audits/issues/2876)
