### ISSUE TITLE
Audit issue verification for @lindseywild

### ISSUE THREAD

**Issue by lindseywild** [lindseywild/commenting-workflow-test#59]
### Description

This is a random sample of audit issues that were validated by @lindseywild.

Validator: please verify that the following issues have been accurately validated and closed. If you find something incorrect, please add a comment to this issue.

### Issues

- [ ] [[WCAG Audit] [NPMSEMPG1.1] [Programmatic Access- NPM semver Page] There are no landmarks defined for 'npm semver calculator' page.](https://github.com/github/accessibility-audits/issues/2870)
- [ ] [[WCAG Audit] [NPMSEMPG1.4] [Keyboard Navigation- NPM semver Page- submit] No error message is displayed upon providing an invalid input in the 'pick a package' edit field.  ](https://github.com/github/accessibility-audits/issues/2875)
- [ ] [[WCAG Audit] [NPMSEMPG1.4] [Screen Reader- NPM semver Page- submit] Upon activation 'Submit' button, screen reader is not announcing any information for the already provided input.](https://github.com/github/accessibility-audits/issues/2876)
- [ ] [[WCAG Audit] [NPMSEMPG1.1] [Programmatic Access- NPM semver Page] Tooltip is not defined for 'submit' button present under 'Pick a package' edit field.](https://github.com/github/accessibility-audits/issues/2866)
- [ ] [[WCAG Audit] [UNISE2.4] [Programmatic Access- Unified search- Results page- Search] For 'Search across repositories' dropdown, state- expanded/collapsed control (^) and role is not defined.](https://github.com/github/accessibility-audits/issues/2814)
